@startuml

(*) --> "Check global counter"

if "global counter >= sampling frequency * symbol length" then
 -->[true] "Update DAC with 0" 
 --> "Disable current interrupt" 
 -right-> "Check lock-free queue for pending symbols"
 if "lock-free queue is not empty" then
   -->[true] "Pop symbol off queue"
   -left->"Set timer duration to inter-symbol spacing" 
   --> "Set timer interrupt handler to callback which starts next tone"
 else
   -right->[false] "Set global flag to false"
 endif
else
 -right->[false] "Generate next tone sample"
 -right-> "Update DAC with the new sample"
 --> "Increment global counter"
endif

@enduml